services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    volumes:
      - .:/workspace
    command: sleep infinity
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
